apiVersion: apps/v1

kind: Deployment
metadata:
  name: flux-dev-1
  namespace: default
  labels:
    app: flux-dev-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux-dev-1
  template:
    metadata:
      labels:
        app: flux-dev-1
    spec:
      affinity: # Pod调度亲和性，选择合适的 GPU 卡型号
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.ebtech.com/gpu
                    operator: In
                    values:
                      - A800_NVLINK_80GB
      volumes:
        # 挂载共享模型数据大盘（如需要）
        - name: models
          hostPath:
            path: /public
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "50Gi"
      containers:
      - name: flux-dev
        image: registry-cn-huabei1-internal.ebcloud.com/job-template/flux_1:dev-build1
        command:
          - bash
          - "-c"
          - |
            cd /root/flux && \
              source .venv/bin/activate && \
              python3 demo_gr.py --name flux-dev
        env:
          - name: HF_DATASETS_OFFLINE
            value: "1"
          - name: TRANSFORMERS_OFFLINE
            value: "1"
          - name: HF_HUB_OFFLINE
            value: "1"
          - name: FLUX_DEV
            value: "/public/huggingface-models/black-forest-labs/FLUX.1-dev/flux1-dev.safetensors"
          - name: AE
            value: "/public/huggingface-models/black-forest-labs/FLUX.1-dev/ae.safetensors"
        ports:
        - containerPort: 7860
        resources:
          limits:
            cpu: "10"
            memory: 100G
            nvidia.com/gpu: "1"
          requests:
            cpu: "10"
            memory: 100G
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: shm
          mountPath: /dev/shm
        # 挂载共享模型数据大盘（如需要）
        - name: models
          mountPath: /public

---


apiVersion: v1
kind: Service
metadata:
  name: flux-dev-1
  namespace: default
spec:
  ports:
  - name: http-flux-dev-1
    port: 80
    protocol: TCP
    targetPort: 7860
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: flux-dev-1
  sessionAffinity: None
  # 指定 LoadBalancer 类型，用于将服务暴露到外部，自动分配公网 IP
  type: ClusterIP