apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-data # 存储卷的名称
spec:
  accessModes:
    - ReadWriteMany # 存储卷的读写模式
  resources:
    requests:
      storage: 1Gi # 存储卷的容量大小
  storageClassName: shared-nvme-cn-huabei1 # 创建存储卷使用的StorageClass的名字

---


apiVersion: apps/v1

kind: Deployment
metadata:
  name: searxng-1
  namespace: default
  labels:
    app: searxng-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng-1
  template:
    metadata:
      labels:
        app: searxng-1
    spec:
      volumes:
        # 挂载分布式存储盘（如需要）
        - name: data
          persistentVolumeClaim:
            claimName: searxng-data
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "10Gi"
        - name: public-data
          hostPath:
            path: /public
      containers:
      - name: searxng
        image: registry-cn-huabei1-internal.ebcloud.com/docker.io/searxng/searxng:latest
        command:
          - sh
          - "-c"
          - |
            rm -f /etc/searxng/settings.yml /etc/searxng/limiter.toml

            if [ ! -f /root/.searxng/settings.yml ]; then
              cp /public/shared-resources/searxng-config/settings.yml /root/.searxng/
            fi
            if [ ! -f /root/.searxng/limiter.toml ]; then
              cp /public/shared-resources/searxng-config/limiter.toml /root/.searxng/
            fi

            cp /root/.searxng/settings.yml /etc/searxng/
            cp /root/.searxng/limiter.toml /etc/searxng/
            # export SEARXNG_BIND_ADDRESS=0.0.0.0
            # export SEARXNG_PORT=8080
            export SEARXNG_SECRET=ABABAB
            # export SEARXNG_LIMITER=true
            # export SEARXNG_PUBLIC_INSTANCE=true
            /usr/local/searxng/dockerfiles/docker-entrypoint.sh
        env:
          - name: HF_ENDPOINT
            value: "https://hf-mirror.com"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "10"
            memory: 20G
          requests:
            cpu: "10"
            memory: 20G
        volumeMounts:
        - name: shm
          mountPath: /dev/shm
        - name: data
          mountPath: /root/.searxng/
          subPath: searxng-data-mount
        - name: public-data
          mountPath: /public

---

apiVersion: v1
kind: Service
metadata:
  name: searxng-1
  namespace: default
spec:
  ports:
  - name: http-searxng-1
    port: 80
    protocol: TCP
    targetPort: 8080
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: searxng-1
  sessionAffinity: None
  # 指定 LoadBalancer 类型，用于将服务暴露到外部，自动分配公网 IP
  type: ClusterIP