apiVersion: apps/v1
kind: Deployment
metadata:
  name: quant-4090
  namespace: default
  labels:
    app: quant-4090
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quant-4090
  template:
    metadata:
      labels:
        app: quant-4090
    spec:
      affinity: # Pod调度亲和性，选择合适的 GPU 卡型号
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.ebtech.com/gpu
                    operator: In
                    values:
                       - RTX_4090
      volumes:
        # 挂载共享模型数据大盘（如需要）
        - name: models
          hostPath:
            path: /public
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "30Gi"
      containers:
      - name: quant-4090
        image: registry-cn-huabei1-internal.ebcloud.com/job-template/consumer-card:20251023
        imagePullPolicy: Always
        command:
          - bash
          - "-c"
          - |
            apt-get update
            apt-get install -y curl openssh-server vim net-tools sysstat sudo
            mkdir -p /etc/ssh
            # echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
            # echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
            # echo "root:YOUR@PASS#WORD" | chpasswd
            # create user ebuser and allow password login
            useradd -m -s /bin/bash -p $(echo "YOUR@PASS#WORD" | openssl passwd -1 -stdin) ebuser
            echo "ebuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
            echo "ebuser:YOUR@PASS#WORD" | chpasswd
            echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
            service ssh start -D
            sleep infinity
        # env:
        #   - name: HF_DATASETS_OFFLINE
        #     value: "1"
        #   - name: TRANSFORMERS_OFFLINE
        #     value: "1"
        #   - name: HF_HUB_OFFLINE
        #     value: "1"
        ports:
        - containerPort: 22
        - containerPort: 8000
        - containerPort: 8080
        resources:
          limits:
            cpu: "10"
            memory: 100G
            nvidia.com/gpu: "1"
          requests:
            cpu: "10"
            memory: 100G
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: shm
          mountPath: /dev/shm
        # 挂载共享模型数据大盘（如需要）
        - name: models
          mountPath: /public
---
apiVersion: v1
kind: Service
metadata:
  name: quant-4090
  namespace: default
spec:
  ports:
  - name: http-quant-4090
    port: 80
    protocol: TCP
    targetPort: 8080
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: quant-4090
  sessionAffinity: None
  # 指定 LoadBalancer 类型，用于将服务暴露到外部，自动分配公网 IP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: quant-4090-ssh
  annotations:
    # metallb.universe.tf/address-pool: sglang-4
    metallb.universe.tf/allow-shared-ip: "cuda-devbox"
spec:
  selector:
    app: quant-4090
  ports:
    - protocol: TCP
      port: 61022
      targetPort: 22
  type: ClusterIP #LoadBalancer
